### PR TITLE
Upgrade analyzer to 0.41.0

### PR DESCRIPTION
**Pull request by agilob**

### CODE REVIEW

**Comment by agilob** [comment]
Actually, I only need it to be >= 0.41 but latest version for dart 2.12 is 1.1.0 so maybe it should go up all the way for your 3.0.0 branch?

**Comment by agilob** [comment]
I have no idea if these error are expected after analyzer change. Can you advise @vanlooverenkoen ?

**Comment by vanlooverenkoen** [comment]
Because of your analyzer change the formatting of the generated code is different so the tests should be updated as wel.

**Comment by vanlooverenkoen** [comment]
For some reason, the analyzer upgrade is failing to resolve the named dependencies.

**Comment by vanlooverenkoen** [comment]
I just tried with 0.41.1 and that is working just fine. 1.1.0 is already used in the nullsafety build. So that could be used there already.

**Comment by vanlooverenkoen** [comment]
Because we are blocked by a lot of dependencies. we are required to wait until everything is updated for the kiwi_generator.

**Comment by agilob** [comment]
Ah ok then

**Comment by agilob** [comment]
For my kiwi_generator is blocking upgrade, because of older version of analyzer which somes with older and conflicting version of yaml...

>Because no versions of kiwi_generator match >=3.0.0-nullsafety.0 <3.0.0-nullsafety-generator.0 or >3.0.0-nullsafety-generator.0 <4.0.0 and kiwi_generator 3.0.0-nullsafety-generator.0 depends on analyzer ^0.40.4, kiwi_generator ^3.0.0-nullsafety.0 requires analyzer ^0.40.4.

>And because analyzer >=0.32.4 <0.41.1 depends on yaml ^2.1.2 and flutter_i18n 0.22.2 depends on yaml ^3.1.0, kiwi_generator ^3.0.0-nullsafety.0 is incompatible with flutter_i18n 0.22.2.

Could you please make a new release with upgraded analyzer?

**Comment by vanlooverenkoen** [comment]
I will do that first thing tomorrow. Current not at home

**Comment by agilob** [comment]
thank you

**Comment by agilob** [comment]
I tried to use it from git:

>Because every version of kiwi_generator from git depends on kiwi ^2.1.1 and agilenow depends on kiwi ^3.0.0-nullsafety.0, kiwi_generator from git is forbidden.

Is this expected? Can I open PR for it?

**Comment by vanlooverenkoen** [comment]
You should be using the nullsafety branch instead. Because master is the stable (non null safety branch for kiwi)
I am currently working on a new release

**Comment by vanlooverenkoen** [comment]
`3.0.0-nullsafety-genertor.1` is available

**Comment by agilob** [comment]
thanks mate!

**Pull request closed without merging**
